### ISSUE TITLE
invalid syntax issue due to is_skipped_an_issue

### ISSUE THREAD

**Issue by anushreeShenoy3** [reportportal/client-Python#72]
Error message while executing report module
File "/home/test/agent/workspace/mv/test_backup/.pyenv/local/lib/python2.7/site-packages/lemoncheesecake/reporting/backends/reportportal.py", line 9, in <module>
    from reportportal_client import ReportPortalServiceAsync
  File "/home/test/agent/workspace/mv/test_backup/.pyenv/local/lib/python2.7/site-packages/reportportal_client/__init__.py", line 15, in <module>
    from .service import ReportPortalService
  File "/home/test/agent/workspace/mv/test_backup/.pyenv/local/lib/python2.7/site-packages/reportportal_client/service.py", line 124
    is_skipped_an_issue=True,
                      ^
SyntaxError: invalid syntax
This is caused due to latest merged code.

**Comment by ndelon** [comment]
It's this commit: https://github.com/reportportal/client-Python/commit/5a6d26de57b58921a642eba53e27ff3a36b0d80c

Having a `*args` before an argument with a default value is not supported in Python 2.7, that's why you get a SyntaxError.

I don't understand the purpose of this change and the `*args` and `**kwargs` variables are not used in this method.

The library used to work in Python 2.7, before 5.0.0. I don't know if the authors want to continue to support Python 2.7 (which is no longer maintained since January 1st) but I guess that Python 2.7 is still used by a lot of people.

**Comment by krasoffski** [comment]
@iivanou 
`setup.py` does not list any python requirements, that is an issue. 
Need to revert commit or update `setup.py` and release notes with supported python versions.

Probably `python2` comes to end of life, that is why core team is focused only python 3 for version 5.
Any way need updated docs and `setup.py`

**Comment by iivanou** [comment]
@ndelon Read through [this article](https://www.geeksforgeeks.org/args-kwargs-python/) to figure out what is the purpose of *args, **kwargs.

Unfortunately, Python 2.7 is being used by loads of people. I forgot about the missing tests. I will fix this soon.

**Comment by ndelon** [comment]
Hopefully, I know what are `*args` and `**kwargs`.
But I do not understand why they have been added in the method signature while they are unused.
And adding `**kwargs` in method signature while it's not used is also not user-friendly. If for instance you make a typo in an argument name (example: `retry` instead of `retries`), instead of having an exception `"...unexpected keyword argument..."` you will have no errors.

**Comment by iivanou** [comment]
@ndelon I make comments in the code if it is necessary. Unfortunately, I can't explain to everyone every piece of written code. Doing this last time... It was done to allow agents' contributors to implement new features without the necessity to update and release two packages at one time.

**Comment by anushreeShenoy3** [comment]
@iivanou Thanks for the updates. I have two projects running in 2.7 and 3+.  Latest code worked fine for 3+. It is not an issue. For 2.7, version 3.2.0 of report client is used in order to avoid conflicts.

**Comment by iivanou** [comment]
@anushreeShenoy3 Which conflicts do you mean? The latest code should work well with RPv5 and Python 2.7.
